name: Docker Image CI

on:
  push:
    branches:
    - experimental
    - latest
    - master
    - '*-release'  # specific to Release Bot

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        IMAGE_TAG=${GITHUB_REF##*/}
        if [ "$IMAGE_TAG" == "master" ]; then
          IMAGE_TAG='latest'
        fi
        docker build . \
          --file build/Dockerfile \ 
          --build-arg GITHUB_REVISION=${GITHUB_REF##*/} \ 
          --tag cermakm/python-release-action:${IMAGE_TAG}
      
    - name: Login to the DockerHub
      run:  docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Push the Docker image to the registry
      run: |
        IMAGE_TAG=${GITHUB_REF##*/}
        if [ "$IMAGE_TAG" == "master" ]; then
          IMAGE_TAG='latest'
        fi
        docker push cermakm/python-release-action:${IMAGE_TAG}

